'use client';

import { useState, useEffect } from 'react';
import styles from './page.module.css';
import { useRouter } from 'next/navigation';

type User = { id: string; name: string; color: string };
type Rect = { x: number; y: number; w: number; h: number };
type OcrItem = { id: string; name: string; price: number; rect: Rect; claimedBy: string[] };

export default function SummaryPage() {
  const router = useRouter();
  const [users, setUsers] = useState<User[]>([]);
  const [items, setItems] = useState<OcrItem[]>([]);
  const [taxAndService, setTaxAndService] = useState(0); 
  const [imageUrl, setImageUrl] = useState<string | null>(null);

  const [isImageExpanded, setIsImageExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    const storedUsers = sessionStorage.getItem('snapsplit_users');
    const storedItems = sessionStorage.getItem('snapsplit_items');
    const storedTax = sessionStorage.getItem('snapsplit_tax');
    const storedImage = sessionStorage.getItem('snapsplit_image');
    
    if (storedUsers) setUsers(JSON.parse(storedUsers));
    if (storedItems) setItems(JSON.parse(storedItems));
    if (storedTax) setTaxAndService(parseInt(storedTax, 10) || 0);
    if (storedImage) setImageUrl(storedImage);
  }, []);

  if (users.length === 0 || items.length === 0) return null;

  // Calculate Subtotals
  const totalSubtotal = items.reduce((sum, item) => sum + item.price, 0);
  
  const userTotals = users.map(user => {
    let subtotal = 0;
    const userItems: OcrItem[] = [];

    items.forEach(item => {
      if (item.claimedBy.includes(user.id)) {
        subtotal += (item.price / item.claimedBy.length);
        userItems.push(item);
      }
    });

    // Proportional Tax Allocation
    // If you ate 30% of the total food, you pay 30% of the tax
    const sharePercentage = totalSubtotal > 0 ? (subtotal / totalSubtotal) : 0;
    const taxShare = taxAndService * sharePercentage;
    const finalTotal = subtotal + taxShare;

    return {
      ...user,
      subtotal,
      taxShare,
      finalTotal,
      userItems
    };
  });

  const unassignedItems = items.filter(i => i.claimedBy.length === 0);
  const totalUnassigned = unassignedItems.reduce((s, i) => s + i.price, 0);
  const grandTotal = totalSubtotal + taxAndService;

  const getSharedNames = (claimedBy: string[], currentUserId: string) => {
    return claimedBy
      .filter(id => id !== currentUserId)
      .map(id => users.find(u => u.id === id)?.name)
      .filter(Boolean)
      .join(', ');
  };

  const handleCopyText = () => {
    let text = 'Split Bill Summary\n\n';

    userTotals.forEach(u => {
      text += `${u.name}\n`;
      u.userItems.forEach(item => {
        let itemLine = `- ${item.name}`;
        if (item.claimedBy.length > 1) {
          itemLine += ` (Shared with: ${getSharedNames(item.claimedBy, u.id)})`;
        }
        text += `${itemLine}\n`;
      });
      text += `Subtotal: Rp ${Math.round(u.subtotal).toLocaleString()}\n`;
      if (u.taxShare > 0) {
        text += `Tax & Service: Rp ${Math.round(u.taxShare).toLocaleString()}\n`;
      }
      text += `Total: Rp ${Math.round(u.finalTotal).toLocaleString()}\n\n`;
    });

    if (unassignedItems.length > 0) {
      text += `Unassigned Items: Rp ${Math.round(totalUnassigned).toLocaleString()}\n\n`;
    }

    text += `Grand Total: Rp ${Math.round(grandTotal).toLocaleString()}\n\n`;
    text += `Generated by stevenmulya@gmail.com`;

    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <main className={styles.main}>
      <div className={styles.container}>
        <div className={styles.header}>
          <h1 className={styles.title}>Bill Summary</h1>
          <p className={styles.subtitle}>Review the calculated totals for each participant.</p>
        </div>

        {imageUrl && (
          <>
            <div 
              className={styles.receiptImageContainer}
              onClick={() => setIsImageExpanded(true)}
              title="Click to expand"
            >
              <img src={imageUrl} alt="Receipt" className={styles.receiptImage} />
            </div>

            {isImageExpanded && (
              <div 
                className={styles.imageOverlay}
                onClick={() => setIsImageExpanded(false)}
              >
                <img src={imageUrl} alt="Receipt Full" className={styles.expandedImage} />
              </div>
            )}
          </>
        )}

        <div className={styles.receiptContainer}>
          {userTotals.map(u => (
            <div key={u.id} className={styles.userSection} style={{ borderTop: `4px solid var(--color-${u.color})` }}>
              <div className={styles.userHeader}>
                <h2>{u.name}</h2>
                <h2>Rp {Math.round(u.finalTotal).toLocaleString()}</h2>
              </div>
              
              <ul className={styles.itemList}>
                {u.userItems.map(item => (
                  <li key={item.id}>
                    <div className={styles.itemDetails}>
                      <span className={styles.itemName}>{item.name}</span>
                      {item.claimedBy.length > 1 && (
                        <span className={styles.sharedNames}>
                          (Shared with: {getSharedNames(item.claimedBy, u.id)})
                        </span>
                      )}
                    </div>
                    <span className={styles.itemPrice}>Rp {Math.round(item.price / item.claimedBy.length).toLocaleString()}</span>
                  </li>
                ))}
              </ul>

              <div className={styles.mathBreakdown}>
                <div><span>Subtotal</span> <span>Rp {Math.round(u.subtotal).toLocaleString()}</span></div>
                <div><span>Proportional Tax & Service</span> <span>Rp {Math.round(u.taxShare).toLocaleString()}</span></div>
              </div>
            </div>
          ))}

          {unassignedItems.length > 0 && (
            <div className={styles.unassignedWarning}>
              <strong>Warning:</strong> {unassignedItems.length} items (Rp {totalUnassigned.toLocaleString()}) were not claimed by anyone!
            </div>
          )}
        </div>

        <div className={styles.grandTotalSection}>
          <h2>Grand Total</h2>
          <h2>Rp {Math.round(grandTotal).toLocaleString()}</h2>
        </div>

        <div className={styles.footer}>
          <button 
            onClick={handleCopyText}
            className={styles.secondaryButton}
          >
            {copied ? 'Copied!' : 'Copy Bill Summary'}
          </button>
          <button 
            onClick={() => {
              sessionStorage.clear();
              router.push('/');
            }}
            className={styles.primaryButton}
          >
            Start New Bill
          </button>
        </div>
      </div>
    </main>
  );
}
